/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author albert
 */

import Reader.CodeReader;
import Reader.BinDecConverter;
import Generator.DecBinConverter;
import Generator.CodeGenerator;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.File;
import java.util.Random;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

public class BarCodes extends javax.swing.JFrame {
    private String decimal;
    private boolean[] barBoolean;
    private BufferedImage barCode;
    private String path;
    
    private JLabel BarLabel;
    private JLabel DecimalLabel;
    private JButton SaveButton;

    /**
     * Creates new form MainFrame
     */
    public BarCodes() {
        initComponents();
                
        BarLabel = new JLabel();
        BarLabel.setSize(Display.getWidth(), Display.getHeight());       
        BarLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                
        DecimalLabel = new JLabel();
        DecimalLabel.setSize(Display.getWidth(), Display.getHeight());
        DecimalLabel.setFont(new Font("Arial", Font.PLAIN, 30));;
        DecimalLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        SaveButton = new JButton("Save");
        SaveButton.setSize(50, 23);
        SaveButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        SaveButton.setVisible(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
              
        Display.setLayout(new BoxLayout(Display, BoxLayout.Y_AXIS));        
        Display.add(Box.createVerticalGlue());
        Display.add(BarLabel);
        Display.add(Box.createRigidArea(new Dimension(0, 30)));
        Display.add(DecimalLabel);
        Display.add(Box.createRigidArea(new Dimension(0, 10)));
        Display.add(SaveButton);
        Display.add(Box.createVerticalGlue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerateButton = new javax.swing.JButton();
        ReadButton = new javax.swing.JButton();
        Display = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar Codes Generator/Reader");

        GenerateButton.setText("Generate Bar Code");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        ReadButton.setText("Read Bar Code");
        ReadButton.setPreferredSize(new java.awt.Dimension(180, 23));
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
        Display.setLayout(DisplayLayout);
        DisplayLayout.setHorizontalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DisplayLayout.setVerticalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(GenerateButton)
                        .addGap(34, 34, 34)
                        .addComponent(ReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateButton))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("Bars"));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();
        
        try {
            barCode = ImageIO.read(file);          
        } catch (IOException e) {
            System.out.println("Error reading image:" + e);
        }
        
        ImageIcon barIcon = new ImageIcon(barCode);
        Image scaledImage = barIcon.getImage().getScaledInstance(270, 100, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        
        barBoolean = CodeReader.read(barCode);
        decimal = BinDecConverter.generate(barBoolean);
        
        BarLabel.setIcon(scaledIcon);       
        BarLabel.setBorder(new CompoundBorder(BorderFactory.createLineBorder(Color.BLACK), new EmptyBorder(10, 20, 10, 20)));
        DecimalLabel.setText(decimal);
        SaveButton.setVisible(true);
    }//GEN-LAST:event_ReadButtonActionPerformed

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        Random generator = new Random();
        decimal = "";
        for (int i = 0; i <= 8 - 1; i++) {
            int digit = generator.nextInt(10);
            decimal += "" + digit;
        }
        String binary = DecBinConverter.generate(Integer.parseInt(decimal));
        barBoolean = DecBinConverter.generateBool(binary);

        CodeGenerator.build(decimal, barBoolean);
        barCode = CodeGenerator.getBarCode();

        ImageIcon barIcon = new ImageIcon(barCode);
        Image scaledImage = barIcon.getImage().getScaledInstance(270, 100, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        BarLabel.setIcon(scaledIcon);   
        BarLabel.setBorder(new CompoundBorder(BorderFactory.createLineBorder(Color.BLACK), new EmptyBorder(10, 20, 10, 20)));
        DecimalLabel.setText(decimal);
        SaveButton.setVisible(true);
    }//GEN-LAST:event_GenerateButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        CodeGenerator.save(decimal, barCode);
        path = CodeGenerator.getPath();
        JOptionPane.showMessageDialog(rootPane, "Saved in: \n" + path);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarCodes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JButton ReadButton;
    // End of variables declaration//GEN-END:variables
}
