/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author albert
 */

import javax.swing.*;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.File;
import java.util.Random;
import Gerador.*;
import Leitor.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

public class MainFrame extends javax.swing.JFrame {
    private String decimal;
    private boolean[] barBoolean;
    private BufferedImage barCode;
    private String path;
    
    private JLabel BarLabel;
    private JLabel DecimalLabel;
    private JButton BotaoSalvar;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
                
        BarLabel = new JLabel();
        BarLabel.setSize(Display.getWidth(), Display.getHeight());       
        BarLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                
        DecimalLabel = new JLabel();
        DecimalLabel.setSize(Display.getWidth(), Display.getHeight());
        DecimalLabel.setFont(new Font("Arial", Font.PLAIN, 30));;
        DecimalLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        BotaoSalvar = new JButton("Salvar");
        BotaoSalvar.setSize(50, 23);
        BotaoSalvar.setAlignmentX(Component.CENTER_ALIGNMENT);
        BotaoSalvar.setVisible(false);
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
              
        Display.setLayout(new BoxLayout(Display, BoxLayout.Y_AXIS));        
        Display.add(Box.createVerticalGlue());
        Display.add(BarLabel);
        Display.add(Box.createRigidArea(new Dimension(0, 30)));
        Display.add(DecimalLabel);
        Display.add(Box.createRigidArea(new Dimension(0, 10)));
        Display.add(BotaoSalvar);
        Display.add(Box.createVerticalGlue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoGerar = new javax.swing.JButton();
        BotaoLer = new javax.swing.JButton();
        Display = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador/Leitor de Código de Barras");

        BotaoGerar.setText("Gerar Código de Barras");
        BotaoGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerarActionPerformed(evt);
            }
        });

        BotaoLer.setText("Ler Código de Barras");
        BotaoLer.setPreferredSize(new java.awt.Dimension(180, 23));
        BotaoLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLerActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
        Display.setLayout(DisplayLayout);
        DisplayLayout.setHorizontalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DisplayLayout.setVerticalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addComponent(BotaoGerar)
                        .addGap(34, 34, 34)
                        .addComponent(BotaoLer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoLer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoGerar))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLerActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("BarCodes"));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();
        
        try {
            barCode = ImageIO.read(file);          
        } catch (IOException e) {
            System.out.println("Erro ao ler a imagem: " + e);
        }
        
        ImageIcon barIcon = new ImageIcon(barCode);
        Image scaledImage = barIcon.getImage().getScaledInstance(270, 100, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        
        barBoolean = LeitorDeCodigo.read(barCode);
        decimal = ConversorBinDec.gerar(barBoolean);
        
        BarLabel.setIcon(scaledIcon);       
        BarLabel.setBorder(new CompoundBorder(BorderFactory.createLineBorder(Color.BLACK), new EmptyBorder(10, 20, 10, 20)));
        DecimalLabel.setText(decimal);
        BotaoSalvar.setVisible(true);
    }//GEN-LAST:event_BotaoLerActionPerformed

    private void BotaoGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerarActionPerformed
        Random gerador = new Random();
        decimal = "";
        for (int i = 0; i <= 8 - 1; i++) {
            int digito = gerador.nextInt(10);
            decimal += "" + digito;
        }
        String binario = ConversorDecBin.gerar(Integer.parseInt(decimal));
        barBoolean = ConversorDecBin.gerarBool(binario);

        GeradorDeCodigo.build(decimal, barBoolean);
        barCode = GeradorDeCodigo.getBarCode();

        ImageIcon barIcon = new ImageIcon(barCode);
        Image scaledImage = barIcon.getImage().getScaledInstance(270, 100, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        BarLabel.setIcon(scaledIcon);   
        BarLabel.setBorder(new CompoundBorder(BorderFactory.createLineBorder(Color.BLACK), new EmptyBorder(10, 20, 10, 20)));
        DecimalLabel.setText(decimal);
        BotaoSalvar.setVisible(true);
    }//GEN-LAST:event_BotaoGerarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        GeradorDeCodigo.save(decimal, barCode);
        path = GeradorDeCodigo.getPath();
        JOptionPane.showMessageDialog(rootPane, "Salvo em: \n" + path);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGerar;
    private javax.swing.JButton BotaoLer;
    private javax.swing.JPanel Display;
    // End of variables declaration//GEN-END:variables
}
